---
- block:

  - name: 'bloodhound : check for existing installation'
    stat: path=/usr/local/bin/bloodhound
    register: bloodhound

  - name: 'bloodhound : download binary release from repository'
    get_url:
      url: https://github.com/BloodHoundAD/BloodHound/releases/download/4.0.3/BloodHound-linux-x64.zip
      dest: /tmp/BloodHound-linux-x64.zip
      mode: '0440'
    when: not bloodhound.stat.exists

  - name: 'bloodhound : unpack archive'
    unarchive:
      src: /tmp/BloodHound-linux-x64.zip
      dest: /opt
      remote_src: yes
    when: not bloodhound.stat.exists

  - name: 'bloodhound : symlink'
    file:
      src: /opt/BloodHound-linux-x64/BloodHound
      dest: /usr/local/bin/bloodhound
      state: link
    when: not bloodhound.stat.exists

  - name: 'bloodhound : cleanup'
    file:
      dest: /tmp/BloodHound-linux-x64.zip
      state: absent
    when: not bloodhound.stat.exists

  tags:
    - exploitation
    - bloodhound
