---
- block:

  - name: 'cobaltstrike : check for existing installation'
    stat: path=/opt/cobaltstrike/cobaltstrike
    register: cobaltstrike

  - name: 'cobaltstrike : extract cobaltstrike archive'
    unarchive:
      dest: /opt
      group: adm
      mode: 0770
      owner: root      
      src: roles/exploitation/files/cobaltstrike-dist.tar.gz
    when: not cobaltstrike.stat.exists

  tags:
    - exploitation
    - cobaltstrike