---
- block:

  - name: 'metasploit : check for existing installation'
    stat: path=/opt/metasploit-framework
    register: msf

  - name: 'metasploit : download installer'
    get_url:
      url: https://raw.githubusercontent.com/rapid7/metasploit-omnibus/master/config/templates/metasploit-framework-wrappers/msfupdate.erb
      dest: /tmp/msfinstall
      mode: 0755
    when: not msf.stat.exists

  - name: 'metasploit : run msfinstall'
    command: /tmp/msfinstall
    when: not msf.stat.exists
  
  - name: 'metasploit : cleanup temporary files'
    file:
      path: /tmp/msfinstall
      state: absent
    
  - name: 'metasploit : add wrapper for exploit tools'
    template:
      dest: /usr/local/bin/{{ item }}
      mode: 0755
      src: ../templates/msf_ruby_wrapper.sh
    with_items:
      - egghunter
      - exe2vba
      - exe2vbs
      - find_badchars
      - java_deserializer
      - jsobfu
      - metasm_shell
      - msf_irb_shell
      - msu_finder
      - nasm_shell
      - pattern_create
      - pattern_offset
      - pdf2xdp
      - psexec
      - random_compile_c
      - reg
      - virustotal

  - name: 'metasploit : create data directory in system directory'
    file:
      path: /usr/share/metasploit-framework/data
      state: directory

  - name: 'metasploit : create wordlist directories'
    file:
      mode: 0755
      path: /usr/share/wordlists
      state: directory

  - name: 'metasploit : add symlinks to wordlist files'
    file:
      path: '{{ item }}'
      src: /opt/metasploit-framework/embedded/framework/data/wordlists
      state: link
    with_items:
      - /usr/share/metasploit-framework/data/wordlists
      - /usr/share/wordlists/metasploit

  tags:
    - exploitation
    - metasploit