---
- block:

  - name: 'powersploit : clone repository'
    git:
      accept_hostkey: yes
      clone: yes
      depth: 1
      dest: /opt/powersploit
      force: yes
      repo: https://github.com/PowerShellMafia/PowerSploit.git

  tags:
    - exploitation
    - powersploit