---
- block:

  - name: 'responder : check for existing installation'
    stat: path=/usr/share/local/responder
    register: responder

  - name: 'responder : clone repository'
    git:
      accept_hostkey: yes
      clone: yes
      depth: 1
      dest: /usr/share/responder
      force: yes
      repo: https://github.com/lgandx/Responder.git

  - name: 'responder : Change to python3'
    ansible.builtin.replace:
      path: /usr/share/responder/Responder.py
      regexp: '^#!/usr/bin/env python$'
      replace: '#!/usr/bin/env python3'

  - name: 'responder : create symlink'
    file:
      dest: /usr/local/bin/responder
      src: /usr/share/responder/Responder.py
      state: link

  tags:
    - exploitation
    - responder      