---
- block:

  - name: 'packages : update apt cache'
    apt:
      update_cache: yes

  - name: 'packages : install common packages'
    apt:
      name:
        - apt-transport-https
        - build-essential
        - python3
        - python3-pip
        - docker
        - docker.io
        - terminator
        - git
        - curl
        - smbclient
        - unzip
        - p7zip-full
        - proxychains4
        - socat
        - vim
        - nmap
        - openvpn
        - wireshark
        - golang-go
        - gcc-mingw-w64-x86-64
        - rlwrap
        - ruby
        - ruby-rubygems
        - rustc
        - cargo
        - default-jre
        - nasm
        - hydra
        - snmp
        - inetutils-traceroute
        - net-tools
        - tshark
        - nikto
        - rdesktop
        - freerdp2-x11
        - sshuttle
        - upx
        - krb5-user
        - azure-cli
        - awscli
        - hashcat
        - ldap-utils
      state: present

  - name: 'packages : install common Python modules'
    pip:
      name:
        - impacket
        - sqlmap
        - bloodhound
        - crackmapexec
        - pipenv
        - virtualenv

  - name: 'packages : add 3rd party apt keys : sublimetext'
    apt_key:
      url: https://download.sublimetext.com/sublimehq-pub.gpg
      state: present

  - name: 'packages : add 3rd party apt repos : sublimetext'
    apt_repository:
      repo: deb https://download.sublimetext.com/ apt/stable/

  - name: 'packages : add 3rd party apt software'
    apt:
      name:
        - sublime-text
      state: present

  tags:
    - common
    - packages
